export interface PluginItem {
  id: string;
  name: string;
  slug: string;
  description: string;
  version: string;
  icon: string;
  author: string;
  category: string;
  capabilities: string[];
  isInstalled: boolean;
  isActive: boolean;
}

export const pluginCatalog: PluginItem[] = [
  // CRM
  {
    id: 'crm-contacts',
    name: 'Contacts',
    slug: 'crm-contacts',
    description: 'Manage your contacts with detailed profiles, notes, and interaction history.',
    version: '2.4.1',
    icon: 'Users',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Contact Management', 'Tags & Segments', 'Import/Export'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-companies',
    name: 'Companies',
    slug: 'crm-companies',
    description: 'Track companies and organizations with hierarchy and relationship mapping.',
    version: '2.3.0',
    icon: 'Building2',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Company Profiles', 'Hierarchy', 'Deal Pipeline'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-deals',
    name: 'Deals',
    slug: 'crm-deals',
    description: 'Track sales deals with pipeline stages, values, and probability scoring.',
    version: '2.5.2',
    icon: 'DollarSign',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Deal Pipeline', 'Forecasting', 'Win/Loss Analysis'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-pipeline',
    name: 'Pipeline',
    slug: 'crm-pipeline',
    description: 'Visual pipeline management with drag-and-drop stage progression.',
    version: '2.2.0',
    icon: 'GitBranch',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Kanban View', 'Drag & Drop', 'Auto-Progression'],
    isInstalled: true,
    isActive: false,
  },
  {
    id: 'crm-activities',
    name: 'Activities',
    slug: 'crm-activities',
    description: 'Log calls, meetings, emails, and other activities across your CRM.',
    version: '1.9.3',
    icon: 'Activity',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Activity Logging', 'Calendar Sync', 'Reminders'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-notes',
    name: 'Notes',
    slug: 'crm-notes',
    description: 'Rich text notes linked to contacts, companies, and deals.',
    version: '1.5.0',
    icon: 'StickyNote',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Rich Text', 'Mentions', 'Attachments'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-tasks',
    name: 'Tasks',
    slug: 'crm-tasks',
    description: 'Create and assign tasks with due dates, priorities, and follow-ups.',
    version: '2.1.4',
    icon: 'CheckSquare',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Task Management', 'Priorities', 'Due Dates'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-calendar',
    name: 'Calendar',
    slug: 'crm-calendar',
    description: 'Shared calendar with scheduling, availability, and meeting links.',
    version: '1.8.2',
    icon: 'Calendar',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Scheduling', 'Meeting Links', 'Sync'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'crm-email',
    name: 'Email',
    slug: 'crm-email',
    description: 'Integrated email client with templates, sequences, and tracking.',
    version: '2.0.1',
    icon: 'Mail',
    author: 'AENEWS',
    category: 'CRM',
    capabilities: ['Email Templates', 'Sequences', 'Open Tracking'],
    isInstalled: true,
    isActive: false,
  },

  // ERP / Finance
  {
    id: 'erp-finance',
    name: 'Finance',
    slug: 'erp-finance',
    description: 'Complete financial management with ledgers, journals, and reporting.',
    version: '3.1.0',
    icon: 'Landmark',
    author: 'AENEWS',
    category: 'ERP',
    capabilities: ['General Ledger', 'Journals', 'Financial Reports'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'erp-accounting',
    name: 'Accounting',
    slug: 'erp-accounting',
    description: 'Double-entry accounting with chart of accounts and reconciliation.',
    version: '3.0.5',
    icon: 'Calculator',
    author: 'AENEWS',
    category: 'ERP',
    capabilities: ['Double-Entry', 'Chart of Accounts', 'Reconciliation'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'erp-tax',
    name: 'Tax',
    slug: 'erp-tax',
    description: 'Tax management with automated calculations and filing support.',
    version: '2.2.1',
    icon: 'Receipt',
    author: 'AENEWS',
    category: 'ERP',
    capabilities: ['Tax Calculation', 'Filing Support', 'Reports'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'erp-inventory',
    name: 'Inventory',
    slug: 'erp-inventory',
    description: 'Track inventory levels, warehouses, stock movements, and valuations.',
    version: '2.8.3',
    icon: 'Package',
    author: 'AENEWS',
    category: 'ERP',
    capabilities: ['Stock Tracking', 'Warehouses', 'Valuation'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'erp-procurement',
    name: 'Procurement',
    slug: 'erp-procurement',
    description: 'Manage purchase orders, vendor relationships, and supply chain.',
    version: '1.7.0',
    icon: 'Truck',
    author: 'AENEWS',
    category: 'ERP',
    capabilities: ['Purchase Orders', 'Vendors', 'Supply Chain'],
    isInstalled: false,
    isActive: false,
  },

  // HR
  {
    id: 'hr-employees',
    name: 'Employees',
    slug: 'hr-employees',
    description: 'Comprehensive employee profiles with documents and history.',
    version: '2.3.1',
    icon: 'UserCog',
    author: 'AENEWS',
    category: 'HR',
    capabilities: ['Employee Profiles', 'Documents', 'Org Chart'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'hr-payroll',
    name: 'Payroll',
    slug: 'hr-payroll',
    description: 'Automated payroll processing with tax calculations and payslips.',
    version: '2.1.0',
    icon: 'Wallet',
    author: 'AENEWS',
    category: 'HR',
    capabilities: ['Payroll Processing', 'Tax Calc', 'Payslips'],
    isInstalled: true,
    isActive: false,
  },
  {
    id: 'hr-leave',
    name: 'Leave',
    slug: 'hr-leave',
    description: 'Leave management with balances, requests, and approval workflows.',
    version: '1.9.2',
    icon: 'CalendarOff',
    author: 'AENEWS',
    category: 'HR',
    capabilities: ['Leave Balances', 'Requests', 'Approvals'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'hr-recruitment',
    name: 'Recruitment',
    slug: 'hr-recruitment',
    description: 'End-to-end recruitment with job postings, applicants, and interviews.',
    version: '2.0.0',
    icon: 'UserPlus',
    author: 'AENEWS',
    category: 'HR',
    capabilities: ['Job Postings', 'Applicant Tracking', 'Interviews'],
    isInstalled: false,
    isActive: false,
  },

  // Healthcare
  {
    id: 'health-patients',
    name: 'Patients',
    slug: 'health-patients',
    description: 'Patient records management with medical history and demographics.',
    version: '1.4.0',
    icon: 'Heart',
    author: 'AENEWS',
    category: 'Healthcare',
    capabilities: ['Patient Records', 'Medical History', 'Demographics'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'health-doctors',
    name: 'Doctors',
    slug: 'health-doctors',
    description: 'Doctor profiles with specialties, schedules, and availability.',
    version: '1.3.2',
    icon: 'Stethoscope',
    author: 'AENEWS',
    category: 'Healthcare',
    capabilities: ['Doctor Profiles', 'Schedules', 'Specialties'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'health-consultations',
    name: 'Consultations',
    slug: 'health-consultations',
    description: 'Manage consultations, diagnoses, treatment plans, and follow-ups.',
    version: '1.2.1',
    icon: 'ClipboardList',
    author: 'AENEWS',
    category: 'Healthcare',
    capabilities: ['Consultations', 'Diagnosis', 'Treatment Plans'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'health-prescriptions',
    name: 'Prescriptions',
    slug: 'health-prescriptions',
    description: 'Digital prescriptions with drug interactions and dosage tracking.',
    version: '1.1.0',
    icon: 'Pill',
    author: 'AENEWS',
    category: 'Healthcare',
    capabilities: ['Digital Prescriptions', 'Drug Interactions', 'Dosage'],
    isInstalled: false,
    isActive: false,
  },

  // Education
  {
    id: 'edu-students',
    name: 'Students',
    slug: 'edu-students',
    description: 'Student information system with enrollment, grades, and attendance.',
    version: '1.5.0',
    icon: 'GraduationCap',
    author: 'AENEWS',
    category: 'Education',
    capabilities: ['Student Records', 'Enrollment', 'Attendance'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'edu-exams',
    name: 'Exams',
    slug: 'edu-exams',
    description: 'Exam creation, scheduling, grading, and result analysis.',
    version: '1.3.1',
    icon: 'FileQuestion',
    author: 'AENEWS',
    category: 'Education',
    capabilities: ['Exam Creation', 'Scheduling', 'Grading'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'edu-grades',
    name: 'Grades',
    slug: 'edu-grades',
    description: 'Grade book with GPA calculation, transcripts, and report cards.',
    version: '1.4.0',
    icon: 'BarChart3',
    author: 'AENEWS',
    category: 'Education',
    capabilities: ['Grade Book', 'GPA', 'Transcripts'],
    isInstalled: false,
    isActive: false,
  },

  // Real Estate
  {
    id: 're-properties',
    name: 'Properties',
    slug: 're-properties',
    description: 'Property listings with details, images, virtual tours, and pricing.',
    version: '1.6.0',
    icon: 'Home',
    author: 'AENEWS',
    category: 'Real Estate',
    capabilities: ['Property Listings', 'Virtual Tours', 'Pricing'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 're-contracts',
    name: 'Contracts',
    slug: 're-contracts',
    description: 'Lease and sale contract management with e-signatures.',
    version: '1.2.0',
    icon: 'FileSignature',
    author: 'AENEWS',
    category: 'Real Estate',
    capabilities: ['Contract Templates', 'E-Signatures', 'Tracking'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 're-rentals',
    name: 'Rentals',
    slug: 're-rentals',
    description: 'Rental payment tracking, tenant management, and maintenance requests.',
    version: '1.1.2',
    icon: 'Key',
    author: 'AENEWS',
    category: 'Real Estate',
    capabilities: ['Payment Tracking', 'Tenant Management', 'Maintenance'],
    isInstalled: false,
    isActive: false,
  },

  // Manufacturing
  {
    id: 'mfg-machines',
    name: 'Machines',
    slug: 'mfg-machines',
    description: 'Machine registry with maintenance schedules and performance monitoring.',
    version: '1.3.0',
    icon: 'Cog',
    author: 'AENEWS',
    category: 'Manufacturing',
    capabilities: ['Machine Registry', 'Maintenance', 'Performance'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'mfg-production',
    name: 'Production',
    slug: 'mfg-production',
    description: 'Production planning, work orders, and shop floor management.',
    version: '1.4.1',
    icon: 'Factory',
    author: 'AENEWS',
    category: 'Manufacturing',
    capabilities: ['Production Planning', 'Work Orders', 'Shop Floor'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'mfg-quality',
    name: 'Quality',
    slug: 'mfg-quality',
    description: 'Quality control with inspections, non-conformances, and CAPA.',
    version: '1.2.0',
    icon: 'ShieldCheck',
    author: 'AENEWS',
    category: 'Manufacturing',
    capabilities: ['Quality Control', 'Inspections', 'CAPA'],
    isInstalled: false,
    isActive: false,
  },

  // Marketing
  {
    id: 'mkt-campaigns',
    name: 'Campaigns',
    slug: 'mkt-campaigns',
    description: 'Multi-channel campaign management with analytics and attribution.',
    version: '2.0.0',
    icon: 'Megaphone',
    author: 'AENEWS',
    category: 'Marketing',
    capabilities: ['Campaign Builder', 'Analytics', 'Attribution'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'mkt-email-marketing',
    name: 'Email Marketing',
    slug: 'mkt-email-marketing',
    description: 'Email marketing automation with drag-and-drop builder and A/B testing.',
    version: '1.8.3',
    icon: 'Mail',
    author: 'AENEWS',
    category: 'Marketing',
    capabilities: ['Email Builder', 'A/B Testing', 'Automation'],
    isInstalled: false,
    isActive: false,
  },

  // Support
  {
    id: 'sup-tickets',
    name: 'Tickets',
    slug: 'sup-tickets',
    description: 'Support ticket management with SLA tracking and escalation rules.',
    version: '2.2.0',
    icon: 'Headphones',
    author: 'AENEWS',
    category: 'Support',
    capabilities: ['Ticket Management', 'SLA Tracking', 'Escalation'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'sup-chat',
    name: 'Live Chat',
    slug: 'sup-chat',
    description: 'Real-time live chat with chatbots, canned responses, and analytics.',
    version: '1.5.2',
    icon: 'MessageSquare',
    author: 'AENEWS',
    category: 'Support',
    capabilities: ['Live Chat', 'Chatbots', 'Canned Responses'],
    isInstalled: true,
    isActive: false,
  },
  {
    id: 'sup-knowledge-base',
    name: 'Knowledge Base',
    slug: 'sup-knowledge-base',
    description: 'Self-service knowledge base with articles, categories, and search.',
    version: '1.3.0',
    icon: 'BookOpen',
    author: 'AENEWS',
    category: 'Support',
    capabilities: ['Articles', 'Categories', 'Search'],
    isInstalled: true,
    isActive: true,
  },

  // Project
  {
    id: 'proj-kanban',
    name: 'Kanban',
    slug: 'proj-kanban',
    description: 'Kanban boards with swimlanes, WIP limits, and card customization.',
    version: '2.1.0',
    icon: 'Columns3',
    author: 'AENEWS',
    category: 'Project',
    capabilities: ['Kanban Boards', 'Swimlanes', 'WIP Limits'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'proj-gantt',
    name: 'Gantt',
    slug: 'proj-gantt',
    description: 'Interactive Gantt charts with dependencies, milestones, and resources.',
    version: '1.4.2',
    icon: 'GanttChart',
    author: 'AENEWS',
    category: 'Project',
    capabilities: ['Gantt Charts', 'Dependencies', 'Milestones'],
    isInstalled: false,
    isActive: false,
  },
  {
    id: 'proj-sprints',
    name: 'Sprints',
    slug: 'proj-sprints',
    description: 'Agile sprint planning with backlog grooming and velocity tracking.',
    version: '1.6.0',
    icon: 'Zap',
    author: 'AENEWS',
    category: 'Project',
    capabilities: ['Sprint Planning', 'Backlog', 'Velocity'],
    isInstalled: true,
    isActive: true,
  },

  // eCommerce
  {
    id: 'eco-catalog',
    name: 'Catalog',
    slug: 'eco-catalog',
    description: 'Product catalog management with variants, images, and SEO.',
    version: '2.3.1',
    icon: 'ShoppingBag',
    author: 'AENEWS',
    category: 'eCommerce',
    capabilities: ['Product Catalog', 'Variants', 'SEO'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'eco-cart',
    name: 'Cart',
    slug: 'eco-cart',
    description: 'Shopping cart with promotions, discounts, and abandoned cart recovery.',
    version: '2.0.0',
    icon: 'ShoppingCart',
    author: 'AENEWS',
    category: 'eCommerce',
    capabilities: ['Shopping Cart', 'Promotions', 'Recovery'],
    isInstalled: true,
    isActive: true,
  },
  {
    id: 'eco-payments',
    name: 'Payments',
    slug: 'eco-payments',
    description: 'Payment processing with Stripe, PayPal, and multi-currency support.',
    version: '1.9.4',
    icon: 'CreditCard',
    author: 'AENEWS',
    category: 'eCommerce',
    capabilities: ['Payment Processing', 'Multi-Currency', 'Refunds'],
    isInstalled: true,
    isActive: true,
  },
];

export const pluginCategories = [
  'All',
  'CRM',
  'ERP',
  'HR',
  'Healthcare',
  'Education',
  'Real Estate',
  'Manufacturing',
  'Marketing',
  'Support',
  'Project',
  'eCommerce',
];
